# This patch transformer resolves the 'sas-rabbitmq-server' pod failures on Kubernetes with the error, below - when adding or removing StatefulSet nodes on AWS EKS.
 
 # " [error] Cookie file /rabbitmq/data/.erlang.cookie must be accessible by owner only " 

# In your site-config directory, set up overlay sub-directory as such -> rabbitmq/configuration/rabbitmq-node-security.yaml.

---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: rabbitmq-node-security
patch: |-
  - op: replace
    path: /spec/template/spec/containers/0/securityContext
    value:
      runAsUser: 1001
      allowPrivilegeEscalation: false
      capabilities:
        add: []
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
target:
  group: apps
  name: sas-rabbitmq-server
  kind: StatefulSet
  version: v1
